name: auto-deploy

on:
  push:
    branches:
      - 'main'
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into Production Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_SSH_KEY }}
          script: |
            # Stop and remove existing containers
            sudo docker stop prod_site
            sudo docker rm prod_site
            sudo docker rmi sbn-web

            # Pull the latest source code
            git pull origin main

            # Build and start the new Docker containers
            sudo docker build -t sbn-web
            sudo docker run --name prod_site -p 1234:1234 sbn-web
